In [2]:
import cv2 as cv
import numpy as np
import os
import glob

In [3]:
# Run this to make sure you have opencv installed
print(cv.__version__)

3.4.2


In [4]:
# This block finds object points and image points in both camera images, these are needed for cv.stereoCalibrate()
#-------------------------------------------------------------------------------------
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((9*6,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpointss = [] # 2d points in image plane.
imgpointsj = [] # 2d points in image plane.
# Change the directory to a folder that have two folders(each folder should have images fo a camera)
%cd "C:\Users\Ahmed Wagih\Desktop\wedTry\calib"
# change "s7" and "j8" to be the names of the folders that contain images of each camera
imagess = glob.glob("s7\*.jpg")
imagesj = glob.glob("j8\*.jpg")
# two arrays to hold the names of good pictures from both Cams
fnamesAr = [] # file names of s that are true
fnamejAr = [] # file names of j that are true
# loop on each image
for (fnames, fnamej) in zip(imagess, imagesj):
    print("s -> "+ fnames)
    print("j -> "+ fnamej)
    # Read images
    imgss = cv.imread(fnames)
    imgsj = cv.imread(fnamej)
    # convert to gray
    grays = cv.cvtColor(imgss, cv.COLOR_BGR2GRAY)
    grayj = cv.cvtColor(imgsj, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    rets, cornerss = cv.findChessboardCorners(grays, (9,6), None)
    retj, cornersj = cv.findChessboardCorners(grayj, (9,6), None)
    # If found, add object points, image points (after refining them)
    if rets == True and retj == True:
        print("True")
        fnamesAr.append(fnames)
        fnamejAr.append(fnamej)
        objpoints.append(objp)
        imgpointss.append(cornerss)
        imgpointsj.append(cornersj)
        print("-----------------------------------------------------------------------------------")
cv.destroyAllWindows()

C:\Users\Ahmed Wagih\Desktop\wedTry\calib
s -> s7\20200417_220252.jpg
j -> j8\20200417_220255.jpg
s -> s7\20200417_220303.jpg
j -> j8\20200417_220305.jpg
True
-----------------------------------------------------------------------------------
s -> s7\20200417_220314.jpg
j -> j8\20200417_220316.jpg
s -> s7\20200417_220335.jpg
j -> j8\20200417_220337.jpg
s -> s7\20200417_220345.jpg
j -> j8\20200417_220347.jpg
s -> s7\20200417_220356.jpg
j -> j8\20200417_220358.jpg
True
-----------------------------------------------------------------------------------
s -> s7\20200417_220413.jpg
j -> j8\20200417_220416.jpg
s -> s7\20200417_220428.jpg
j -> j8\20200417_220429.jpg
True
-----------------------------------------------------------------------------------
s -> s7\20200417_220442.jpg
j -> j8\20200417_220444.jpg
s -> s7\20200417_220458.jpg
j -> j8\20200417_220500.jpg
True
-----------------------------------------------------------------------------------
s -> s7\20200417_220522.jpg
j -> j8\202004

In [79]:
# save the output data in a file
fil = open("stereoImagesData.txt", "a")
fil.write("fnamesAr is " + str(fnamesAr) + "\n\n\n")
fil.write("fnamejAr is " + str(fnamejAr) + "\n\n\n")
fil.write("objpoints is " + str(objpoints) + "\n\n\n")
fil.write("imgpointss is " + str(imgpointss) + "\n\n\n")
fil.write("imgpointsj is " + str(imgpointsj) + "\n\n\n")
fil.close()

In [5]:
# Data here can be retrieved from github file camera params, these were calculated previously using "Calibrate-Cam.ipynb"

camMats = np.array([[2.80774228e+03, 0.00000000e+00, 2.10378410e+03],
                    [0.00000000e+00, 2.80883263e+03, 1.62033177e+03],
                    [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
distCoeffss = np.array([[-0.12953256,  0.20065338,  0.00661181,  0.00732438,  0.09754305]])

camMatj = np.array([[3.21633266e+03, 0.00000000e+00, 2.44700710e+03],
            [0.00000000e+00, 3.21720389e+03, 1.69378545e+03],
            [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
distCoeffsj = np.array([[ 0.07325807, -0.51734651,  0.00242078,  0.01843635,  0.68931158]])

[[ 0.07325807 -0.51734651  0.00242078  0.01843635  0.68931158]]


In [65]:
# Get the R & T of the stereo setup, these are needed for cv.stereoRectify()
imageSize=(3024, 4032)
retval, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, R, T, E, F = cv.stereoCalibrate(objectPoints=objpoints,
                                        imagePoints1=imgpointss, imagePoints2=imgpointsj,
                                        cameraMatrix1=camMats, distCoeffs1=distCoeffss,
                                        cameraMatrix2=camMatj, distCoeffs2=distCoeffsj,
                                        imageSize=imageSize, flags=cv.CALIB_FIX_INTRINSIC)

[[ 0.32197184]
 [-3.71658705]
 [ 0.85354884]]


'\n\n                                        \n'

In [78]:
# add comment here
R1, R2, P1, P2, Q, validPixROI1, validPixROI2 = cv.stereoRectify(cameraMatrix1, distCoeffs1,
                                                                 cameraMatrix2, distCoeffs2,
                                                                 imageSize, R, T)

[[3.42255206e+03 0.00000000e+00 2.22442541e+03 0.00000000e+00]
 [0.00000000e+00 3.42255206e+03 2.21246651e+03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]]


'\n#kjdlsamk\n= cv.stereoRectify(cameraMatrix1, cameraMatrix2,\n                                                                distCoeffs1, distCoeffs2,\n                                                                imageSize, R, T,\n                                                                flags=CV_CALIB_ZERO_DISPARITY,\n                                                                alpha=-1, newImageSize=(3024, 4032)) \n                                                                '